set(PACKAGE_VERSION "0.16.8")

if(${PACKAGE_FIND_VERSION_PATCH} EQUAL 8)
    message(STATUS "RSBProtocol: Matching wire-format version (8)")
    set(PACKAGE_VERSION "0.16.8")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
    message("RSBProtocol: Wire-format version mismatch; Requested: ${PACKAGE_FIND_VERSION_PATCH}; Provided: 8")
    message("This is not a problem as long as a compatible version of RSBProtocol is found later.")
    message("This message is generated from ${CMAKE_CURRENT_LIST_FILE}")
    message("In general, this can happen when RSB or some other library is configured to use a version of RSBProtocol with which it is not compatible.")
    message("* Did you update the cpp sub-project of RSB, but not the protocol sub-project?")
    message("* Did you install the protocol sub-project after updating?")
    message("* Make sure that the correct version of the protocol sub-project is used if you installed multiple RSB versions in parallel.")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()

if("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_EXACT TRUE)
endif()
